spring:
  application:
    name: order-service
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 3000
            loggerLevel: full
          product-service:
            connectTimeout: 2000
            readTimeout: 3000
            loggerLevel: full
          user-service:
            connectTimeout: 2000
            readTimeout: 3000
            loggerLevel: basic

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.vietmart.order_service.client: DEBUG
